name: Docker Build and Push

on: workflow_dispatch

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: login to registry
        run: docker login -u "$DOCKER_LOGIN" -p ${{ secrets.DOCKER_TOKEN }}

      - name: set a image tag
        run: |
          IMAGE_TAG="latest"
          if [ -n "${{ github.sha }}" ]; then
            IMAGE_TAG="${{ github.sha }}"
          fi
          echo "Image Tag: $IMAGE_TAG" >> $GITHUB_ENV

      - name: build and push an image
        run: |
          docker build -t $DOCKER_LOGIN/my-image:$IMAGE_TAG .
          docker push $DOCKER_LOGIN/my-image:$IMAGE_TAG